export const SET_CURRENT_LAYER = 'SET_CURRENT_LAYER'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const SET_STYLE = 'SET_STYLE'
export const SET_LAYER = 'SET_LAYER'
export const SET_PROJECT_ID = 'SET_PROJECT_ID'
export const SET_LOADING = 'SET_LOADING'